// Date: 2014-06-19 11:39:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package gmail.wumbleminky.powerlines.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLamp extends ModelBase
{
  //fields
    ModelRenderer HeadBottom;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer HeadTop1;
    ModelRenderer HeadTop2;
    ModelRenderer HeadTop3;
    ModelRenderer HeadTop4;
    ModelRenderer Pole;
  
  public ModelLamp()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      HeadBottom = new ModelRenderer(this, 0, 0);
      HeadBottom.addBox(-3.5F, 0F, -3.5F, 7, 1, 7);
      HeadBottom.setRotationPoint(0F, 2F, 0F);
      HeadBottom.setTextureSize(64, 32);
      HeadBottom.mirror = true;
      setRotation(HeadBottom, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 25, 15);
      Shape2.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape2.setRotationPoint(-3F, -4F, -3F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 25, 15);
      Shape3.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape3.setRotationPoint(2F, -4F, -3F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 25, 15);
      Shape4.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape4.setRotationPoint(-3F, -4F, 2F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 25, 15);
      Shape5.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape5.setRotationPoint(2F, -4F, 2F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      HeadTop1 = new ModelRenderer(this, 0, 0);
      HeadTop1.addBox(-3.5F, 0F, -3.5F, 7, 1, 7);
      HeadTop1.setRotationPoint(0F, -5F, 0F);
      HeadTop1.setTextureSize(64, 32);
      HeadTop1.mirror = true;
      setRotation(HeadTop1, 0F, 0F, 0F);
      HeadTop2 = new ModelRenderer(this, 0, 8);
      HeadTop2.addBox(-3F, 0F, -3F, 6, 1, 6);
      HeadTop2.setRotationPoint(0F, -6F, 0F);
      HeadTop2.setTextureSize(64, 32);
      HeadTop2.mirror = true;
      setRotation(HeadTop2, 0F, 0F, 0F);
      HeadTop3 = new ModelRenderer(this, 0, 15);
      HeadTop3.addBox(-2.5F, 0F, -2.5F, 5, 1, 5);
      HeadTop3.setRotationPoint(0F, -7F, 0F);
      HeadTop3.setTextureSize(64, 32);
      HeadTop3.mirror = true;
      setRotation(HeadTop3, 0F, 0F, 0F);
      HeadTop4 = new ModelRenderer(this, 0, 21);
      HeadTop4.addBox(-2F, 0F, -2F, 4, 1, 4);
      HeadTop4.setRotationPoint(0F, -8F, 0F);
      HeadTop4.setTextureSize(64, 32);
      HeadTop4.mirror = true;
      setRotation(HeadTop4, 0F, 0F, 0F);
      Pole = new ModelRenderer(this, 31, 0);
      Pole.addBox(-1F, 0F, -1F, 2, 21, 2);
      Pole.setRotationPoint(0F, 3F, 0F);
      Pole.setTextureSize(64, 32);
      Pole.mirror = true;
      setRotation(Pole, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    HeadBottom.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    HeadTop1.render(f5);
    HeadTop2.render(f5);
    HeadTop3.render(f5);
    HeadTop4.render(f5);
    Pole.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
